import pandas as pd

itemType_map = {
    "BAKERY": "Grocery",
    "COMM BREAD": "Grocery",
    "DAIRY": "Perishable Grocery",
    "DSD GROCERY": "Grocery",
    "FROZEN FOODS": "Perishable Grocery",
    "GROCERY DRY GOODS": "Grocery",
    "LIQUOR,WINE,BEER": "Grocery",
    "MEAT - FRESH & FROZEN": "Perishable Grocery",
    "PRE PACKED DELI": "Perishable Grocery",
    "PRODUCE": "Perishable Grocery",
    "SEAFOOD": "Perishable Grocery",
    "SERVICE DELI": "Perishable Grocery",
    "CANDY, TOBACCO, COOKIES": "Grocery",
    "ACCESSORIES": "Fashion",
    "BOYS WEAR": "Fashion",
    "BRAS & SHAPEWEAR": "Fashion",
    "GIRLS WEAR, 4-6X  AND 7-14": "Fashion",
    "INFANT APPAREL": "Fashion",
    "JEWELRY AND SUNGLASSES": "Fashion",
    "LADIES SOCKS": "Fashion",
    "LADIESWEAR": "Fashion",
    "MENS WEAR": "Fashion",
    "MENSWEAR": "Fashion",
    "PLUS AND MATERNITY": "Fashion",
    "SHEER HOSIERY": "Fashion",
    "SHOES": "Fashion",
    "SLEEPWEAR/FOUNDATIONS": "Fashion",
    "SWIMWEAR/OUTERWEAR": "Fashion",
    "BEDDING": "Home",
    "COOK AND DINE": "Home",
    "FURNITURE": "Home",
    "HOME DECOR": "Home",
    "HOME MANAGEMENT": "Home",
    "LARGE HOUSEHOLD GOODS": "Home",
    "HOUSEHOLD PAPER GOODS": "Home",
    "BATH AND SHOWER": "Health & Beauty",
    "BEAUTY": "Health & Beauty",
    "HEALTH AND BEAUTY AIDS": "Health & Beauty",
    "OPTICAL - FRAMES": "Health & Beauty",
    "OPTICAL - LENSES": "Health & Beauty",
    "PERSONAL CARE": "Health & Beauty",
    "PHARMACY OTC": "Health & Beauty",
    "PHARMACY RX": "Health & Beauty",
    "CAMERAS AND SUPPLIES": "Electronics",
    "ELECTRONICS": "Electronics",
    "MEDIA AND GAMING": "Electronics",
    "PLAYERS AND ELECTRONICS": "Electronics",
    "WIRELESS": "Electronics",
    "1-HR PHOTO": "Electronics",
    "HARDWARE": "Home Improvement",
    "PAINT AND ACCESSORIES": "Home Improvement",
    "SPORTING GOODS": "Sports & Outdoors",
    "AUTOMOTIVE": "Auto",
    "TOYS": "Toys",
    "INFANT CONSUMABLE HARDLINES": "Toys",
    "HORTICULTURE AND ACCESS": "Garden",
    "LAWN AND GARDEN": "Garden",
    "PETS AND SUPPLIES": "Pets",
    "HOUSEHOLD CHEMICALS/SUPP": "Cleaning",
    "FABRICS AND CRAFTS": "Arts & Crafts",
    "BOOKS AND MAGAZINES": "Miscellaneous",
    "CELEBRATION": "Miscellaneous",
    "OFFICE SUPPLIES": "Miscellaneous",
    "SEASONAL": "Miscellaneous",
    "IMPULSE MERCHANDISE": "Miscellaneous",
    "CONCEPT STORES": "Miscellaneous",
    "FINANCIAL SERVICES": "Miscellaneous",
    "OTHER DEPARTMENTS": "Miscellaneous",
}

input_path = "OrderDataset(Original).csv"
output_path = "OrderDataset(Mapped).csv"

df = pd.read_csv(input_path)
df["MappedDepartment"] = df["DepartmentDescription"].map(itemType_map).fillna("Miscellaneous")
df.to_csv(output_path, index=False)

print(f"done, saved to {output_path}")
print(df["MappedDepartment"].value_counts())